package com.mobileai.overlay

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.SimpleViewManager
import com.facebook.react.uimanager.ThemedReactContext
import com.facebook.react.uimanager.ViewManagerDelegate
import com.facebook.react.uimanager.annotations.ReactProp

/**
 * New Architecture (Fabric) ViewManager for MobileAIFloatingOverlay.
 *
 * Used when newArchEnabled=true in the consuming app's gradle.properties.
 * Loaded via the newarch/ sourceSet in build.gradle.
 *
 * Codegen generates FloatingOverlayNativeComponentSpec from src/specs/FloatingOverlayNativeComponent.ts.
 * This class implements the generated spec interface for Fabric rendering.
 */
class FloatingOverlayViewManager(
  private val reactApplicationContext: ReactApplicationContext
) : SimpleViewManager<FloatingOverlayView>() {

  // Fabric: delegate is generated by Codegen. Null until Codegen runs.
  // The interop layer uses this delegate to bridge JS<->Native in New Arch.
  private val delegate: ViewManagerDelegate<FloatingOverlayView>? = try {
    // Codegen generates this class during the build. It may not exist yet in dev setups.
    Class.forName("com.mobileai.overlay.FloatingOverlayNativeComponentSpecDelegate")
      .getConstructor(SimpleViewManager::class.java)
      .newInstance(this) as? ViewManagerDelegate<FloatingOverlayView>
  } catch (e: Exception) {
    // Codegen hasn't run yet or interop is disabled — proceed without delegate
    null
  }

  override fun getDelegate(): ViewManagerDelegate<FloatingOverlayView>? = delegate

  override fun getName(): String = NAME

  override fun createViewInstance(context: ThemedReactContext): FloatingOverlayView {
    return FloatingOverlayView(context)
  }

  companion object {
    const val NAME = "MobileAIFloatingOverlay"
  }
}
