// ─── Shared Menu Data ───────────────────────────────────────

export interface MenuItem {
  name: string;
  price: number;
  description: string;
  category: string;
  ingredients?: string;
}

export const MENUS: Record<string, MenuItem[]> = {
  Pizzas: [
    { name: 'Margherita', price: 10, description: 'Classic tomato & mozzarella', category: 'Pizzas', ingredients: 'Tomato sauce, fresh mozzarella, basil' },
    { name: 'BBQ Chicken', price: 14, description: 'BBQ sauce, chicken & red onion', category: 'Pizzas', ingredients: 'BBQ sauce, grilled chicken, red onion, cilantro' },
    { name: 'Veggie Supreme', price: 12, description: 'Bell peppers, mushrooms & olives', category: 'Pizzas', ingredients: 'Bell peppers, mushrooms, olives, onions, tomato sauce' },
    { name: 'Pepperoni', price: 13, description: 'Classic pepperoni with extra cheese', category: 'Pizzas', ingredients: 'Pepperoni, mozzarella, tomato sauce' },
    { name: 'Hawaiian', price: 12, description: 'Ham, pineapple & mozzarella', category: 'Pizzas', ingredients: 'Ham, pineapple, mozzarella, tomato sauce' },
    { name: 'Four Cheese', price: 15, description: 'Mozzarella, cheddar, parmesan & gorgonzola', category: 'Pizzas', ingredients: 'Mozzarella, cheddar, parmesan, gorgonzola' },
    { name: 'Meat Lovers', price: 16, description: 'Pepperoni, sausage, bacon & ham', category: 'Pizzas', ingredients: 'Pepperoni, Italian sausage, bacon, ham' },
    { name: 'Spicy Diavola', price: 14, description: 'Spicy salami and chili flakes', category: 'Pizzas', ingredients: 'Spicy salami, chili flakes, mozzarella, tomato sauce' },
    { name: 'Truffle Mushroom', price: 18, description: 'Wild mushrooms with truffle oil', category: 'Pizzas', ingredients: 'Wild mushrooms, truffle oil, mozzarella, white sauce' },
    { name: 'Buffalo Chicken', price: 15, description: 'Spicy buffalo sauce and ranch', category: 'Pizzas', ingredients: 'Buffalo sauce, chicken, mozzarella, ranch drizzle' },
    { name: 'Prosciutto e Rucola', price: 16, description: 'Prosciutto, arugula & parmesan', category: 'Pizzas', ingredients: 'Prosciutto, arugula, parmesan shavings, olive oil' },
    { name: 'Capricciosa', price: 14, description: 'Mushrooms, artichokes, ham & olives', category: 'Pizzas', ingredients: 'Mushrooms, artichokes, ham, olives, mozzarella' },
    { name: 'Napoletana', price: 11, description: 'Anchovies, capers & oregano', category: 'Pizzas', ingredients: 'Anchovies, capers, oregano, tomato sauce, mozzarella' },
    { name: 'Calzone', price: 14, description: 'Folded pizza with ricotta & ham', category: 'Pizzas', ingredients: 'Ricotta, ham, mozzarella, tomato sauce' },
    { name: 'Pesto Chicken', price: 15, description: 'Basil pesto with grilled chicken', category: 'Pizzas', ingredients: 'Basil pesto, grilled chicken, mozzarella, sun-dried tomatoes' },
    { name: 'White Pizza', price: 13, description: 'Olive oil, garlic & ricotta base', category: 'Pizzas', ingredients: 'Olive oil, garlic, ricotta, mozzarella, fresh herbs' },
    { name: 'Fig & Prosciutto', price: 17, description: 'Fresh figs with prosciutto & gorgonzola', category: 'Pizzas', ingredients: 'Fresh figs, prosciutto, gorgonzola, arugula, honey drizzle' },
    { name: 'Smoked Salmon', price: 18, description: 'Smoked salmon with cream cheese', category: 'Pizzas', ingredients: 'Smoked salmon, cream cheese, capers, red onion, dill' },
    { name: 'Mushroom Truffle', price: 17, description: 'Assorted mushrooms with truffle cream', category: 'Pizzas', ingredients: 'Porcini, shiitake, oyster mushrooms, truffle cream, fontina' },
    { name: 'Spinach & Feta', price: 13, description: 'Fresh spinach with crumbled feta', category: 'Pizzas', ingredients: 'Fresh spinach, feta cheese, garlic, olive oil, mozzarella' },
    { name: 'Siciliana', price: 14, description: 'Eggplant, capers & pecorino', category: 'Pizzas', ingredients: 'Roasted eggplant, capers, pecorino, tomato sauce' },
    { name: 'Tuna & Onion', price: 13, description: 'Italian tuna with red onion', category: 'Pizzas', ingredients: 'Italian tuna, red onion, capers, mozzarella, tomato sauce' },
    { name: 'Quattro Stagioni', price: 15, description: 'Four seasons with different toppings', category: 'Pizzas', ingredients: 'Artichokes, ham, mushrooms, olives (one per quadrant)' },
    { name: 'Burrata Pizza', price: 19, description: 'Creamy burrata with cherry tomatoes', category: 'Pizzas', ingredients: 'Burrata, cherry tomatoes, basil, olive oil, prosciutto' },
    { name: 'Nduja Pizza', price: 15, description: 'Spicy Calabrian nduja spread', category: 'Pizzas', ingredients: 'Nduja, mozzarella, red onion, honey drizzle' },
    { name: 'Greek Pizza', price: 14, description: 'Feta, olives, peppers & onions', category: 'Pizzas', ingredients: 'Feta, kalamata olives, bell peppers, red onion, oregano' },
    { name: 'Potato Rosemary', price: 12, description: 'Thinly sliced potato with rosemary', category: 'Pizzas', ingredients: 'Sliced potato, fresh rosemary, garlic, olive oil, mozzarella' },
    { name: 'Chorizo & Jalapeño', price: 14, description: 'Spicy chorizo with pickled jalapeños', category: 'Pizzas', ingredients: 'Chorizo, pickled jalapeños, mozzarella, cilantro' },
    { name: 'Tartufo Nero', price: 20, description: 'Black truffle with fontina cheese', category: 'Pizzas', ingredients: 'Black truffle paste, fontina, mozzarella, parmesan, arugula' },
    { name: 'Marinara', price: 9, description: 'Simple tomato, garlic & oregano (no cheese)', category: 'Pizzas', ingredients: 'San Marzano tomatoes, garlic, oregano, extra virgin olive oil' },
  ],
  Burgers: [
    { name: 'Classic Smash', price: 11, description: 'Beef patty, lettuce & tomato', category: 'Burgers', ingredients: 'Beef patty, lettuce, tomato, pickles, special sauce' },
    { name: 'Cheese Burger', price: 13, description: 'Double cheese, pickles & onion', category: 'Burgers', ingredients: 'Beef patty, cheddar cheese x2, pickles, onion' },
    { name: 'Chicken Burger', price: 12, description: 'Crispy chicken with mayo', category: 'Burgers', ingredients: 'Crispy chicken fillet, mayo, lettuce' },
    { name: 'Mushroom Swiss', price: 14, description: 'Sautéed mushrooms & Swiss cheese', category: 'Burgers', ingredients: 'Beef patty, sautéed mushrooms, Swiss cheese' },
    { name: 'Spicy Jalapeño', price: 13, description: 'Jalapeños, pepper jack & hot sauce', category: 'Burgers', ingredients: 'Beef patty, jalapeños, pepper jack cheese, hot sauce' },
    { name: 'Veggie Burger', price: 11, description: 'Plant-based patty with avocado', category: 'Burgers', ingredients: 'Plant-based patty, avocado, lettuce, tomato' },
    { name: 'Bacon Blue', price: 15, description: 'Blue cheese and crispy bacon', category: 'Burgers', ingredients: 'Beef patty, blue cheese crumbles, bacon, caramelized onions' },
    { name: 'The Monster', price: 18, description: 'Triple patty loaded burger', category: 'Burgers', ingredients: 'Three beef patties, bacon, egg, cheese, onion rings' },
    { name: 'BBQ Bacon', price: 14, description: 'BBQ sauce, bacon & cheddar', category: 'Burgers', ingredients: 'Beef patty, BBQ sauce, bacon, cheddar, onion rings' },
    { name: 'Truffle Burger', price: 19, description: 'Truffle aioli & gruyère', category: 'Burgers', ingredients: 'Beef patty, truffle aioli, gruyère cheese, arugula' },
    { name: 'Teriyaki Burger', price: 14, description: 'Teriyaki glaze & grilled pineapple', category: 'Burgers', ingredients: 'Beef patty, teriyaki sauce, grilled pineapple, lettuce' },
    { name: 'Guacamole Burger', price: 15, description: 'Fresh guacamole & pico de gallo', category: 'Burgers', ingredients: 'Beef patty, guacamole, pico de gallo, pepper jack' },
    { name: 'Crispy Onion Burger', price: 13, description: 'Crispy fried onions & ranch', category: 'Burgers', ingredients: 'Beef patty, crispy onions, ranch dressing, lettuce' },
    { name: 'Peanut Butter Burger', price: 14, description: 'PB, bacon & jalapeños', category: 'Burgers', ingredients: 'Beef patty, peanut butter, bacon, jalapeños' },
    { name: 'Greek Lamb Burger', price: 16, description: 'Lamb patty with tzatziki', category: 'Burgers', ingredients: 'Lamb patty, tzatziki, feta, cucumber, tomato' },
    { name: 'Smokehouse Burger', price: 15, description: 'Smoked gouda & crispy onion', category: 'Burgers', ingredients: 'Beef patty, smoked gouda, crispy onions, chipotle mayo' },
    { name: 'Western Burger', price: 14, description: 'Onion rings & BBQ sauce', category: 'Burgers', ingredients: 'Beef patty, onion rings, BBQ sauce, cheddar' },
    { name: 'Breakfast Burger', price: 13, description: 'Fried egg, bacon & hash brown', category: 'Burgers', ingredients: 'Beef patty, fried egg, bacon, hash brown, American cheese' },
    { name: 'Portobello Burger', price: 12, description: 'Grilled portobello cap', category: 'Burgers', ingredients: 'Portobello mushroom, roasted peppers, goat cheese, arugula' },
    { name: 'Bison Burger', price: 17, description: 'Lean bison patty with chipotle', category: 'Burgers', ingredients: 'Bison patty, chipotle mayo, avocado, pepper jack' },
    { name: 'Fish Burger', price: 13, description: 'Battered cod with tartar sauce', category: 'Burgers', ingredients: 'Battered cod fillet, tartar sauce, lettuce, pickles' },
    { name: 'Nashville Hot', price: 14, description: 'Nashville-style hot chicken', category: 'Burgers', ingredients: 'Spicy fried chicken, pickles, coleslaw, hot sauce' },
    { name: 'Wagyu Burger', price: 22, description: 'Premium wagyu beef patty', category: 'Burgers', ingredients: 'Wagyu beef patty, truffle butter, aged cheddar, caramelized onions' },
    { name: 'Cuban Burger', price: 14, description: 'Ham, pickles & Swiss cheese', category: 'Burgers', ingredients: 'Beef patty, ham, Swiss cheese, pickles, mustard' },
    { name: 'Tex-Mex Burger', price: 14, description: 'Chili, cheese & corn chips', category: 'Burgers', ingredients: 'Beef patty, chili con carne, nacho cheese, corn chips' },
    { name: 'Mediterranean Burger', price: 15, description: 'Hummus, roasted peppers & feta', category: 'Burgers', ingredients: 'Beef patty, hummus, roasted red peppers, feta, arugula' },
    { name: 'Korean BBQ Burger', price: 15, description: 'Gochujang glaze & kimchi', category: 'Burgers', ingredients: 'Beef patty, gochujang glaze, kimchi, sesame mayo' },
    { name: 'Pulled Pork Burger', price: 14, description: 'Slow-cooked pulled pork topping', category: 'Burgers', ingredients: 'Beef patty, pulled pork, coleslaw, BBQ sauce' },
    { name: 'Caprese Burger', price: 14, description: 'Fresh mozzarella, tomato & basil', category: 'Burgers', ingredients: 'Beef patty, fresh mozzarella, tomato, basil, balsamic' },
    { name: 'Philly Cheese Burger', price: 15, description: 'Philly cheesesteak style', category: 'Burgers', ingredients: 'Beef patty, sliced steak, provolone, peppers, onions' },
    { name: 'Mac & Cheese Burger', price: 15, description: 'Topped with mac & cheese', category: 'Burgers', ingredients: 'Beef patty, mac and cheese, bacon, jalapeños' },
    { name: 'Aloha Burger', price: 14, description: 'Grilled pineapple & teriyaki', category: 'Burgers', ingredients: 'Beef patty, grilled pineapple, teriyaki sauce, Swiss cheese' },
    { name: 'Ranch Burger', price: 13, description: 'Buttermilk ranch & crispy bacon', category: 'Burgers', ingredients: 'Beef patty, ranch dressing, bacon, lettuce, tomato' },
    { name: 'Buffalo Chicken Burger', price: 13, description: 'Buffalo sauce & blue cheese', category: 'Burgers', ingredients: 'Crispy chicken, buffalo sauce, blue cheese crumbles, celery slaw' },
    { name: 'Elk Burger', price: 18, description: 'Wild elk with huckleberry jam', category: 'Burgers', ingredients: 'Elk patty, huckleberry jam, brie cheese, arugula' },
    { name: 'Chipotle Black Bean', price: 12, description: 'Spiced black bean patty', category: 'Burgers', ingredients: 'Black bean patty, chipotle mayo, avocado, pico de gallo' },
    { name: 'Double Down', price: 16, description: 'Double patty, double cheese', category: 'Burgers', ingredients: 'Two beef patties, American cheese x2, pickles, special sauce' },
    { name: 'Steakhouse Burger', price: 17, description: 'Thick-cut steak burger with A1', category: 'Burgers', ingredients: 'Thick steak patty, A1 sauce, crispy onions, provolone' },
    { name: 'PB&J Burger', price: 13, description: 'Peanut butter & strawberry jam', category: 'Burgers', ingredients: 'Beef patty, peanut butter, strawberry jam, bacon' },
    { name: 'Cajun Burger', price: 14, description: 'Cajun spiced with rémoulade', category: 'Burgers', ingredients: 'Cajun-spiced beef patty, rémoulade sauce, fried green tomato' },
  ],
  Drinks: [
    { name: 'Coke', price: 3, description: 'Coca-Cola 330ml', category: 'Drinks' },
    { name: 'Lemonade', price: 4, description: 'Fresh squeezed lemonade', category: 'Drinks' },
    { name: 'Water', price: 2, description: 'Still mineral water', category: 'Drinks' },
    { name: 'Iced Tea', price: 4, description: 'Peach iced tea', category: 'Drinks' },
    { name: 'Orange Juice', price: 5, description: 'Fresh squeezed orange juice', category: 'Drinks' },
    { name: 'Vanilla Shake', price: 6, description: 'Vanilla milkshake with whipped cream', category: 'Drinks' },
    { name: 'Chocolate Shake', price: 6, description: 'Rich chocolate milkshake', category: 'Drinks' },
    { name: 'Strawberry Shake', price: 6, description: 'Fresh strawberry milkshake', category: 'Drinks' },
    { name: 'Sparkling Water', price: 3, description: 'Carbonated mineral water', category: 'Drinks' },
    { name: 'Mango Lassi', price: 5, description: 'Indian yogurt mango smoothie', category: 'Drinks' },
    { name: 'Espresso', price: 3, description: 'Double shot espresso', category: 'Drinks' },
    { name: 'Cappuccino', price: 5, description: 'Espresso with steamed milk foam', category: 'Drinks' },
    { name: 'Matcha Latte', price: 6, description: 'Japanese matcha with oat milk', category: 'Drinks' },
    { name: 'Cold Brew', price: 5, description: '12-hour cold brew coffee', category: 'Drinks' },
    { name: 'Kombucha', price: 6, description: 'Ginger lemon kombucha', category: 'Drinks' },
    { name: 'Horchata', price: 5, description: 'Mexican cinnamon rice drink', category: 'Drinks' },
    { name: 'Chai Latte', price: 5, description: 'Spiced masala chai with milk', category: 'Drinks' },
    { name: 'Virgin Mojito', price: 6, description: 'Lime, mint & soda water', category: 'Drinks' },
    { name: 'Passion Fruit Juice', price: 5, description: 'Fresh passion fruit juice', category: 'Drinks' },
    { name: 'Ginger Beer', price: 4, description: 'Spicy craft ginger beer', category: 'Drinks' },
    { name: 'Açaí Smoothie', price: 7, description: 'Açaí berry smoothie bowl drink', category: 'Drinks' },
    { name: 'Hot Chocolate', price: 5, description: 'Belgian dark chocolate with cream', category: 'Drinks' },
    { name: 'Arnold Palmer', price: 4, description: 'Half iced tea, half lemonade', category: 'Drinks' },
    { name: 'Coconut Water', price: 4, description: 'Fresh young coconut water', category: 'Drinks' },
    { name: 'Watermelon Juice', price: 5, description: 'Fresh pressed watermelon', category: 'Drinks' },
    { name: 'Turmeric Latte', price: 6, description: 'Golden milk with turmeric & honey', category: 'Drinks' },
    { name: 'Pineapple Juice', price: 5, description: 'Fresh pressed pineapple', category: 'Drinks' },
    { name: 'Rose Lemonade', price: 5, description: 'Lemonade infused with rose water', category: 'Drinks' },
    { name: 'Banana Shake', price: 6, description: 'Banana milkshake with cinnamon', category: 'Drinks' },
    { name: 'Green Juice', price: 7, description: 'Kale, cucumber, apple & ginger', category: 'Drinks' },
  ],
  Desserts: [
    { name: 'Chocolate Cake', price: 7, description: 'Rich chocolate layer cake', category: 'Desserts', ingredients: 'Dark chocolate, cream, flour, eggs' },
    { name: 'Cheesecake', price: 8, description: 'New York style cheesecake', category: 'Desserts', ingredients: 'Cream cheese, graham crackers, vanilla' },
    { name: 'Ice Cream Trio', price: 5, description: 'Three scoops of your choice', category: 'Desserts' },
    { name: 'Tiramisu', price: 9, description: 'Classic Italian tiramisu', category: 'Desserts', ingredients: 'Mascarpone, espresso, ladyfingers, cocoa' },
    { name: 'Apple Pie', price: 6, description: 'Warm apple pie with cinnamon', category: 'Desserts', ingredients: 'Apples, cinnamon, pastry crust' },
    { name: 'Brownie Sundae', price: 8, description: 'Warm brownie with vanilla ice cream', category: 'Desserts', ingredients: 'Fudge brownie, vanilla ice cream, hot fudge' },
    { name: 'Crème Brûlée', price: 9, description: 'Classic French custard with caramelized top', category: 'Desserts', ingredients: 'Egg yolks, heavy cream, vanilla, sugar' },
    { name: 'Panna Cotta', price: 8, description: 'Italian cream dessert with berry sauce', category: 'Desserts', ingredients: 'Heavy cream, vanilla, gelatin, mixed berries' },
    { name: 'Churros', price: 6, description: 'Crispy churros with chocolate dipping sauce', category: 'Desserts', ingredients: 'Flour, butter, cinnamon, dark chocolate sauce' },
    { name: 'Matcha Cake', price: 9, description: 'Japanese matcha green tea cake', category: 'Desserts', ingredients: 'Matcha powder, white chocolate, cream cheese frosting' },
    { name: 'Sticky Toffee Pudding', price: 8, description: 'British sticky date pudding', category: 'Desserts', ingredients: 'Dates, toffee sauce, vanilla ice cream' },
    { name: 'Mochi Ice Cream', price: 7, description: 'Japanese rice cake ice cream balls', category: 'Desserts', ingredients: 'Rice flour, ice cream, sugar' },
    { name: 'Lava Cake', price: 10, description: 'Molten chocolate lava cake', category: 'Desserts', ingredients: 'Dark chocolate, butter, eggs, vanilla ice cream' },
    { name: 'Baklava', price: 7, description: 'Turkish layered phyllo with pistachios', category: 'Desserts', ingredients: 'Phyllo dough, pistachios, honey, butter' },
    { name: 'Key Lime Pie', price: 8, description: 'Tangy key lime pie with graham crust', category: 'Desserts', ingredients: 'Key limes, condensed milk, graham crackers' },
    { name: 'Affogato', price: 6, description: 'Espresso poured over gelato', category: 'Desserts', ingredients: 'Vanilla gelato, double espresso' },
    { name: 'Red Velvet Cake', price: 8, description: 'Red velvet with cream cheese frosting', category: 'Desserts', ingredients: 'Red velvet sponge, cream cheese, buttermilk' },
    { name: 'Cannoli', price: 7, description: 'Sicilian crispy shells with ricotta', category: 'Desserts', ingredients: 'Ricotta, chocolate chips, powdered sugar, pastry shells' },
    { name: 'Fruit Tart', price: 9, description: 'Fresh seasonal fruit on pastry cream', category: 'Desserts', ingredients: 'Shortcrust pastry, pastry cream, seasonal fruit' },
    { name: 'Banoffee Pie', price: 8, description: 'Banana and toffee cream pie', category: 'Desserts', ingredients: 'Bananas, digestive biscuits, toffee, whipped cream' },
    { name: 'Chocolate Mousse', price: 7, description: 'Silky dark chocolate mousse', category: 'Desserts', ingredients: 'Dark chocolate, heavy cream, eggs' },
    { name: 'Profiteroles', price: 8, description: 'Choux puffs with chocolate sauce', category: 'Desserts', ingredients: 'Choux pastry, vanilla cream, chocolate sauce' },
    { name: 'Carrot Cake', price: 7, description: 'Spiced carrot cake with walnuts', category: 'Desserts', ingredients: 'Carrots, walnuts, cinnamon, cream cheese frosting' },
    { name: 'Mango Sorbet', price: 6, description: 'Refreshing mango sorbet', category: 'Desserts', ingredients: 'Fresh mango, sugar, lime juice' },
    { name: 'Bread Pudding', price: 7, description: 'Warm bread pudding with vanilla sauce', category: 'Desserts', ingredients: 'Brioche bread, custard, raisins, vanilla sauce' },
    { name: 'Pistachio Gelato', price: 6, description: 'Authentic Italian pistachio gelato', category: 'Desserts', ingredients: 'Pistachios, milk, cream, sugar' },
    { name: 'Beignets', price: 7, description: 'New Orleans-style fried dough', category: 'Desserts', ingredients: 'Flour, yeast, powdered sugar, butter' },
    { name: 'Pavlova', price: 9, description: 'Meringue with fresh berries & cream', category: 'Desserts', ingredients: 'Egg whites, sugar, fresh berries, whipped cream' },
    { name: 'Nutella Crêpe', price: 7, description: 'Thin crêpe filled with Nutella', category: 'Desserts', ingredients: 'Crêpe batter, Nutella, sliced bananas, powdered sugar' },
    { name: 'Tres Leches', price: 8, description: 'Three-milk soaked sponge cake', category: 'Desserts', ingredients: 'Sponge cake, condensed milk, evaporated milk, heavy cream' },
  ],
  Salads: [
    { name: 'Caesar Salad', price: 9, description: 'Romaine, croutons, parmesan', category: 'Salads', ingredients: 'Romaine lettuce, croutons, parmesan cheese, Caesar dressing' },
    { name: 'Greek Salad', price: 10, description: 'Feta, olives, cucumber, tomato', category: 'Salads', ingredients: 'Feta cheese, kalamata olives, cucumber, tomatoes, red onion' },
    { name: 'Cobb Salad', price: 12, description: 'Chicken, bacon, egg, blue cheese', category: 'Salads', ingredients: 'Grilled chicken, bacon, hard-boiled egg, blue cheese, avocado' },
    { name: 'Caprese', price: 11, description: 'Fresh mozzarella, tomatoes, basil', category: 'Salads', ingredients: 'Fresh mozzarella, tomatoes, fresh basil, balsamic glaze' },
    { name: 'Waldorf Salad', price: 11, description: 'Apples, celery, walnuts & grapes', category: 'Salads', ingredients: 'Apples, celery, walnuts, grapes, mayo dressing' },
    { name: 'Asian Sesame', price: 12, description: 'Mixed greens with sesame ginger dressing', category: 'Salads', ingredients: 'Mixed greens, edamame, carrots, sesame seeds, ginger dressing' },
    { name: 'Quinoa Bowl', price: 13, description: 'Quinoa with roasted vegetables', category: 'Salads', ingredients: 'Quinoa, roasted sweet potato, chickpeas, kale, tahini' },
    { name: 'Nicoise Salad', price: 13, description: 'Tuna, green beans, olives & egg', category: 'Salads', ingredients: 'Seared tuna, green beans, olives, hard-boiled egg, potatoes' },
    { name: 'Kale & Apple', price: 10, description: 'Massaged kale with apple slices', category: 'Salads', ingredients: 'Kale, apple slices, pecans, cranberries, lemon vinaigrette' },
    { name: 'Fattoush', price: 10, description: 'Lebanese salad with crispy pita', category: 'Salads', ingredients: 'Lettuce, radishes, cucumber, tomato, crispy pita, sumac dressing' },
    { name: 'Tabbouleh', price: 9, description: 'Bulgur wheat with parsley & mint', category: 'Salads', ingredients: 'Bulgur wheat, parsley, mint, tomato, lemon juice, olive oil' },
    { name: 'Spinach & Strawberry', price: 11, description: 'Baby spinach with fresh strawberries', category: 'Salads', ingredients: 'Baby spinach, strawberries, goat cheese, pecans, balsamic' },
    { name: 'Grilled Chicken Salad', price: 13, description: 'Mixed greens with grilled chicken breast', category: 'Salads', ingredients: 'Grilled chicken, mixed greens, avocado, corn, ranch dressing' },
    { name: 'Poke Bowl', price: 14, description: 'Hawaiian-style raw fish salad', category: 'Salads', ingredients: 'Raw tuna, sushi rice, edamame, mango, sesame soy dressing' },
    { name: 'Mediterranean Bowl', price: 12, description: 'Hummus bowl with falafel', category: 'Salads', ingredients: 'Hummus, falafel, cucumber, tomato, pickled onion, tahini' },
    { name: 'Arugula & Pear', price: 11, description: 'Peppery arugula with ripe pear', category: 'Salads', ingredients: 'Arugula, pear slices, gorgonzola, walnuts, honey vinaigrette' },
    { name: 'Roasted Beet', price: 11, description: 'Roasted beets with goat cheese', category: 'Salads', ingredients: 'Roasted beets, goat cheese, arugula, walnuts, balsamic' },
    { name: 'Southwest Salad', price: 12, description: 'Black beans, corn & avocado', category: 'Salads', ingredients: 'Romaine, black beans, corn, avocado, tortilla strips, chipotle ranch' },
    { name: 'Thai Papaya', price: 11, description: 'Green papaya salad with lime', category: 'Salads', ingredients: 'Shredded green papaya, tomato, peanuts, lime, chili, fish sauce' },
    { name: 'Watermelon Feta', price: 10, description: 'Fresh watermelon with feta & mint', category: 'Salads', ingredients: 'Watermelon cubes, feta cheese, fresh mint, lime juice' },
    { name: 'Chopped Italian', price: 11, description: 'Classic Italian chopped salad', category: 'Salads', ingredients: 'Romaine, salami, mozzarella, pepperoncini, chickpeas, Italian dressing' },
    { name: 'Harvest Bowl', price: 13, description: 'Roasted squash & wild rice', category: 'Salads', ingredients: 'Butternut squash, wild rice, dried cranberries, pepitas, maple vinaigrette' },
    { name: 'Avocado Citrus', price: 12, description: 'Avocado with orange segments', category: 'Salads', ingredients: 'Avocado, blood orange, grapefruit, arugula, citrus vinaigrette' },
    { name: 'Shrimp Louie', price: 14, description: 'Classic shrimp salad with Louie dressing', category: 'Salads', ingredients: 'Bay shrimp, iceberg lettuce, tomato, egg, Louie dressing' },
    { name: 'Power Green', price: 12, description: 'Superfood green salad', category: 'Salads', ingredients: 'Kale, spinach, broccoli, avocado, hemp seeds, green goddess dressing' },
    { name: 'Corn & Black Bean', price: 10, description: 'Southwestern corn salad', category: 'Salads', ingredients: 'Roasted corn, black beans, red onion, cilantro, lime dressing' },
    { name: 'Moroccan Couscous', price: 11, description: 'Couscous with dried fruit & almonds', category: 'Salads', ingredients: 'Couscous, dried apricots, almonds, chickpeas, harissa dressing' },
    { name: 'Caesar with Shrimp', price: 14, description: 'Classic Caesar topped with grilled shrimp', category: 'Salads', ingredients: 'Romaine, grilled shrimp, parmesan, croutons, Caesar dressing' },
    { name: 'Detox Salad', price: 11, description: 'Raw vegetable cleanse salad', category: 'Salads', ingredients: 'Cabbage, carrots, beets, apple cider vinegar, turmeric dressing' },
    { name: 'Grilled Halloumi', price: 12, description: 'Grilled halloumi over mixed greens', category: 'Salads', ingredients: 'Halloumi cheese, mixed greens, pomegranate seeds, mint, lemon' },
  ],
  Sushi: [
    { name: 'California Roll', price: 8, description: 'Crab, avocado, cucumber', category: 'Sushi', ingredients: 'Imitation crab, avocado, cucumber, nori, rice' },
    { name: 'Spicy Tuna Roll', price: 9, description: 'Spicy tuna and cucumber', category: 'Sushi', ingredients: 'Spicy tuna mix, cucumber, nori, rice' },
    { name: 'Dragon Roll', price: 14, description: 'Eel and cucumber topped with avocado', category: 'Sushi', ingredients: 'Eel, cucumber, avocado, eel sauce' },
    { name: 'Salmon Sashimi', price: 12, description: '5 pieces of fresh salmon', category: 'Sushi', ingredients: 'Fresh raw salmon' },
    { name: 'Rainbow Roll', price: 15, description: 'California roll topped with assorted fish', category: 'Sushi', ingredients: 'Crab, avocado, tuna, salmon, yellowtail' },
    { name: 'Shrimp Tempura Roll', price: 12, description: 'Crispy shrimp tempura with avocado', category: 'Sushi', ingredients: 'Shrimp tempura, avocado, cucumber, tempura flakes' },
    { name: 'Philadelphia Roll', price: 10, description: 'Smoked salmon with cream cheese', category: 'Sushi', ingredients: 'Smoked salmon, cream cheese, cucumber, rice' },
    { name: 'Tuna Nigiri', price: 8, description: '2 pieces of tuna over rice', category: 'Sushi', ingredients: 'Fresh bluefin tuna, sushi rice, wasabi' },
    { name: 'Salmon Nigiri', price: 8, description: '2 pieces of salmon over rice', category: 'Sushi', ingredients: 'Fresh Atlantic salmon, sushi rice, wasabi' },
    { name: 'Eel Nigiri', price: 10, description: '2 pieces of grilled eel over rice', category: 'Sushi', ingredients: 'Grilled freshwater eel, sushi rice, eel sauce' },
    { name: 'Volcano Roll', price: 14, description: 'Baked spicy crab on top of California roll', category: 'Sushi', ingredients: 'Crab, avocado, spicy mayo, tobiko' },
    { name: 'Caterpillar Roll', price: 13, description: 'Eel roll topped with sliced avocado', category: 'Sushi', ingredients: 'Eel, cucumber, avocado slices, eel sauce' },
    { name: 'Spider Roll', price: 14, description: 'Soft shell crab tempura roll', category: 'Sushi', ingredients: 'Fried soft shell crab, avocado, cucumber, spicy mayo' },
    { name: 'Yellowtail Jalapeño', price: 13, description: 'Yellowtail with jalapeño slices', category: 'Sushi', ingredients: 'Yellowtail sashimi, jalapeño, ponzu, cilantro' },
    { name: 'Rock & Roll', price: 12, description: 'Shrimp tempura with eel on top', category: 'Sushi', ingredients: 'Shrimp tempura, eel, avocado, eel sauce' },
    { name: 'Veggie Roll', price: 7, description: 'Assorted vegetables in rice', category: 'Sushi', ingredients: 'Cucumber, avocado, carrot, asparagus, rice' },
    { name: 'Lobster Roll', price: 18, description: 'Maine lobster tempura roll', category: 'Sushi', ingredients: 'Lobster tempura, avocado, mango, spicy mayo' },
    { name: 'Crispy Rice Spicy Tuna', price: 14, description: 'Spicy tuna on crispy rice cakes', category: 'Sushi', ingredients: 'Spicy tuna tartare, crispy sushi rice, sriracha aioli' },
    { name: 'Salmon Avocado Roll', price: 10, description: 'Fresh salmon with avocado', category: 'Sushi', ingredients: 'Fresh salmon, avocado, rice, nori' },
    { name: 'Scallop Roll', price: 14, description: 'Fresh sea scallop roll', category: 'Sushi', ingredients: 'Fresh sea scallop, avocado, cucumber, tobiko' },
    { name: 'Mango Shrimp Roll', price: 12, description: 'Sweet mango with shrimp', category: 'Sushi', ingredients: 'Cooked shrimp, mango, avocado, sweet chili sauce' },
    { name: 'Tiger Roll', price: 13, description: 'Avocado roll topped with shrimp', category: 'Sushi', ingredients: 'Avocado, cucumber, cooked shrimp on top, eel sauce' },
    { name: 'Unagi Don', price: 16, description: 'Grilled eel over rice bowl', category: 'Sushi', ingredients: 'Grilled eel, sushi rice, eel sauce, pickled ginger' },
    { name: 'Chirashi Bowl', price: 18, description: 'Assorted sashimi over rice', category: 'Sushi', ingredients: 'Tuna, salmon, yellowtail, shrimp, roe, sushi rice' },
    { name: 'Poke Roll', price: 12, description: 'Hawaiian-inspired tuna poke roll', category: 'Sushi', ingredients: 'Marinated tuna, cucumber, avocado, sesame, sriracha' },
    { name: 'Dynamite Roll', price: 13, description: 'Baked scallop and shrimp roll', category: 'Sushi', ingredients: 'Baked scallop, shrimp, avocado, dynamite sauce' },
    { name: 'Crunchy Roll', price: 11, description: 'Spicy crab with tempura crunch', category: 'Sushi', ingredients: 'Spicy crab mix, tempura flakes, avocado, cucumber' },
    { name: 'King Crab Roll', price: 20, description: 'Real king crab leg roll', category: 'Sushi', ingredients: 'King crab leg, avocado, cucumber, tobiko, spicy mayo' },
    { name: 'Torched Salmon Roll', price: 14, description: 'Salmon roll with torched mayo topping', category: 'Sushi', ingredients: 'Salmon, avocado, torched garlic mayo, eel sauce' },
    { name: 'Omakase Platter', price: 35, description: "Chef's choice 12-piece selection", category: 'Sushi', ingredients: "Chef's selection of seasonal nigiri and sashimi" },
  ],
  Breakfast: [
    { name: 'Pancakes', price: 8, description: 'Stack of 3 buttermilk pancakes', category: 'Breakfast', ingredients: 'Flour, buttermilk, butter, maple syrup' },
    { name: 'Avocado Toast', price: 10, description: 'Smashed avocado on sourdough', category: 'Breakfast', ingredients: 'Sourdough bread, avocado, chili flakes, olive oil' },
    { name: 'Eggs Benedict', price: 12, description: 'Poached eggs on English muffin', category: 'Breakfast', ingredients: 'English muffin, poached eggs, ham, hollandaise sauce' },
    { name: 'French Toast', price: 9, description: 'Brioche french toast with berries', category: 'Breakfast', ingredients: 'Brioche bread, eggs, cinnamon, mixed berries' },
    { name: 'Granola Bowl', price: 8, description: 'House-made granola with yogurt', category: 'Breakfast', ingredients: 'Oats, honey, almonds, Greek yogurt, fresh berries' },
    { name: 'Breakfast Burrito', price: 11, description: 'Scrambled eggs, cheese & chorizo', category: 'Breakfast', ingredients: 'Flour tortilla, scrambled eggs, cheese, chorizo, salsa' },
    { name: 'Belgian Waffle', price: 10, description: 'Crispy Belgian waffle with toppings', category: 'Breakfast', ingredients: 'Waffle batter, strawberries, whipped cream, maple syrup' },
    { name: 'Smoked Salmon Bagel', price: 13, description: 'Bagel with smoked salmon & cream cheese', category: 'Breakfast', ingredients: 'Everything bagel, smoked salmon, cream cheese, capers, red onion' },
    { name: 'Shakshuka', price: 11, description: 'Eggs poached in spiced tomato sauce', category: 'Breakfast', ingredients: 'Eggs, tomato sauce, bell peppers, cumin, feta, crusty bread' },
    { name: 'Omelette', price: 10, description: 'Three-egg omelette with your choice', category: 'Breakfast', ingredients: 'Eggs, cheese, mushrooms, spinach, bell peppers' },
    { name: 'Açaí Bowl', price: 12, description: 'Açaí smoothie bowl with toppings', category: 'Breakfast', ingredients: 'Açaí puree, banana, granola, coconut flakes, honey' },
    { name: 'Croque Monsieur', price: 11, description: 'French grilled ham & cheese', category: 'Breakfast', ingredients: 'Sourdough, ham, gruyère, béchamel sauce' },
    { name: 'Huevos Rancheros', price: 11, description: 'Mexican fried eggs on tortillas', category: 'Breakfast', ingredients: 'Corn tortillas, fried eggs, ranchero sauce, black beans, queso' },
    { name: 'Steel-Cut Oatmeal', price: 7, description: 'Slow-cooked steel-cut oats', category: 'Breakfast', ingredients: 'Steel-cut oats, brown sugar, cinnamon, fresh berries, walnuts' },
    { name: 'Breakfast Sandwich', price: 9, description: 'Egg, cheese & bacon on brioche', category: 'Breakfast', ingredients: 'Brioche bun, fried egg, bacon, American cheese, sriracha mayo' },
    { name: 'Chia Pudding', price: 8, description: 'Overnight chia seed pudding', category: 'Breakfast', ingredients: 'Chia seeds, coconut milk, mango, passion fruit, granola' },
    { name: 'Croissant & Jam', price: 6, description: 'Butter croissant with artisan jam', category: 'Breakfast', ingredients: 'Butter croissant, strawberry jam, butter' },
    { name: 'Eggs Florentine', price: 12, description: 'Poached eggs on spinach & muffin', category: 'Breakfast', ingredients: 'English muffin, poached eggs, sautéed spinach, hollandaise' },
    { name: 'Chilaquiles', price: 10, description: 'Fried tortilla strips in salsa verde', category: 'Breakfast', ingredients: 'Tortilla chips, salsa verde, fried eggs, crema, cotija cheese' },
    { name: 'Mushroom Toast', price: 10, description: 'Sautéed mushrooms on sourdough', category: 'Breakfast', ingredients: 'Mixed mushrooms, garlic, thyme, sourdough, goat cheese' },
    { name: 'Smoothie Bowl', price: 11, description: 'Tropical smoothie with toppings', category: 'Breakfast', ingredients: 'Mango, banana, coconut milk, granola, chia seeds, kiwi' },
    { name: 'Corned Beef Hash', price: 12, description: 'Crispy corned beef with potatoes', category: 'Breakfast', ingredients: 'Corned beef, diced potatoes, onions, bell peppers, fried eggs' },
    { name: 'Yogurt Parfait', price: 8, description: 'Layered yogurt with fruit & granola', category: 'Breakfast', ingredients: 'Greek yogurt, mixed berries, granola, honey' },
    { name: 'Brioche French Toast Sticks', price: 9, description: 'Dippable french toast sticks', category: 'Breakfast', ingredients: 'Brioche, eggs, cinnamon, powdered sugar, maple syrup' },
    { name: 'Breakfast Quesadilla', price: 10, description: 'Cheesy egg quesadilla', category: 'Breakfast', ingredients: 'Flour tortilla, scrambled eggs, cheese, peppers, salsa' },
    { name: 'Fruit Plate', price: 9, description: 'Fresh seasonal fruit selection', category: 'Breakfast', ingredients: 'Seasonal fruits, mint, honey drizzle' },
    { name: 'Ricotta Pancakes', price: 11, description: 'Fluffy ricotta pancakes with lemon', category: 'Breakfast', ingredients: 'Ricotta cheese, lemon zest, blueberries, maple syrup' },
    { name: 'Bagel & Lox', price: 14, description: 'Classic bagel with lox platter', category: 'Breakfast', ingredients: 'Sesame bagel, lox, cream cheese, tomato, onion, capers' },
    { name: 'Eggs in a Basket', price: 8, description: 'Egg fried inside toast hole', category: 'Breakfast', ingredients: 'Sourdough bread, egg, butter, salt, pepper' },
    { name: 'Turkish Breakfast', price: 15, description: 'Spread with cheese, olives & bread', category: 'Breakfast', ingredients: 'Feta, olives, tomatoes, cucumber, honey, bread, tea' },
  ],
  Tacos: [
    { name: 'Al Pastor Taco', price: 4, description: 'Marinated pork with pineapple', category: 'Tacos', ingredients: 'Marinated pork, pineapple, onions, cilantro, corn tortilla' },
    { name: 'Carne Asada Taco', price: 5, description: 'Grilled steak', category: 'Tacos', ingredients: 'Grilled steak, onions, cilantro, corn tortilla' },
    { name: 'Fish Taco', price: 5, description: 'Battered fish with cabbage slaw', category: 'Tacos', ingredients: 'White fish, batter, cabbage slaw, creamy sauce, flour tortilla' },
    { name: 'Chicken Tinga', price: 4, description: 'Shredded chicken in tomato chipotle sauce', category: 'Tacos', ingredients: 'Shredded chicken, tomato, chipotle, onions, corn tortilla' },
    { name: 'Carnitas Taco', price: 5, description: 'Slow-cooked pulled pork', category: 'Tacos', ingredients: 'Pulled pork, pickled onion, cilantro, salsa verde, corn tortilla' },
    { name: 'Barbacoa Taco', price: 5, description: 'Slow-braised beef cheeks', category: 'Tacos', ingredients: 'Braised beef, onion, cilantro, lime, corn tortilla' },
    { name: 'Shrimp Taco', price: 6, description: 'Grilled shrimp with mango salsa', category: 'Tacos', ingredients: 'Grilled shrimp, mango salsa, cabbage, chipotle crema, flour tortilla' },
    { name: 'Birria Taco', price: 6, description: 'Beef birria dipped in consommé', category: 'Tacos', ingredients: 'Braised beef, Oaxaca cheese, consommé, cilantro, corn tortilla' },
    { name: 'Lengua Taco', price: 6, description: 'Tender braised beef tongue', category: 'Tacos', ingredients: 'Beef tongue, onion, cilantro, salsa verde, corn tortilla' },
    { name: 'Chorizo Taco', price: 4, description: 'Mexican-style chorizo sausage', category: 'Tacos', ingredients: 'Pork chorizo, onion, cilantro, pineapple, corn tortilla' },
    { name: 'Veggie Taco', price: 4, description: 'Grilled vegetables with queso', category: 'Tacos', ingredients: 'Grilled zucchini, peppers, onions, queso fresco, corn tortilla' },
    { name: 'Cochinita Pibil', price: 5, description: 'Yucatan-style achiote pork', category: 'Tacos', ingredients: 'Achiote pork, pickled red onion, habanero, corn tortilla' },
    { name: 'Suadero Taco', price: 5, description: 'Crispy braised beef brisket', category: 'Tacos', ingredients: 'Beef brisket, salsa roja, onion, cilantro, corn tortilla' },
    { name: 'Mushroom Taco', price: 4, description: 'Sautéed mushrooms with rajas', category: 'Tacos', ingredients: 'Mixed mushrooms, rajas (roasted peppers), crema, corn tortilla' },
    { name: 'Mole Taco', price: 5, description: 'Chicken in dark mole sauce', category: 'Tacos', ingredients: 'Shredded chicken, mole negro, sesame seeds, onion, corn tortilla' },
    { name: 'Gobernador Taco', price: 7, description: 'Shrimp & cheese quesadilla taco', category: 'Tacos', ingredients: 'Shrimp, Oaxaca cheese, poblano, tomato, flour tortilla' },
    { name: 'Campechano Taco', price: 5, description: 'Mixed steak & chorizo', category: 'Tacos', ingredients: 'Grilled steak, chorizo, onion, cilantro, salsa, corn tortilla' },
    { name: 'Nopal Taco', price: 4, description: 'Grilled cactus paddle', category: 'Tacos', ingredients: 'Grilled nopal, queso fresco, pico de gallo, avocado, corn tortilla' },
    { name: 'Fried Avocado Taco', price: 5, description: 'Crispy fried avocado wedges', category: 'Tacos', ingredients: 'Fried avocado, chipotle crema, cabbage slaw, corn tortilla' },
    { name: 'Lamb Barbacoa', price: 7, description: 'Slow-roasted lamb in agave leaves', category: 'Tacos', ingredients: 'Roasted lamb, avocado, onion, cilantro, salsa borracha, corn tortilla' },
    { name: 'Rajas con Queso', price: 4, description: 'Roasted poblano strips with cheese', category: 'Tacos', ingredients: 'Roasted poblano, Oaxaca cheese, crema, corn, corn tortilla' },
    { name: 'Chicharrón Taco', price: 5, description: 'Crispy pork skin in salsa verde', category: 'Tacos', ingredients: 'Pork chicharrón, salsa verde, onion, cilantro, corn tortilla' },
    { name: 'Taco Dorado', price: 5, description: 'Crispy rolled chicken taco', category: 'Tacos', ingredients: 'Shredded chicken, fried corn tortilla, lettuce, crema, queso fresco' },
    { name: 'Alambre Taco', price: 6, description: 'Bacon, steak, peppers & cheese', category: 'Tacos', ingredients: 'Steak, bacon, bell peppers, Oaxaca cheese, onion, flour tortilla' },
    { name: 'Duck Confit Taco', price: 8, description: 'Slow-cooked duck leg', category: 'Tacos', ingredients: 'Duck confit, mole, pickled red onion, microgreens, corn tortilla' },
    { name: 'Octopus Taco', price: 8, description: 'Grilled octopus with chipotle', category: 'Tacos', ingredients: 'Grilled octopus, chipotle aioli, pickled onion, arugula, corn tortilla' },
    { name: 'Potato Taco', price: 3, description: 'Crispy potato with salsa', category: 'Tacos', ingredients: 'Mashed potato, fried corn tortilla, salsa roja, lettuce, crema' },
    { name: 'Tinga de Tinga', price: 4, description: 'Spicy shredded pork tinga', category: 'Tacos', ingredients: 'Pulled pork, chipotle tomato sauce, onion, avocado, corn tortilla' },
    { name: 'Cecina Taco', price: 5, description: 'Thinly sliced salted beef', category: 'Tacos', ingredients: 'Cecina beef, avocado, onion, cilantro, salsa verde, corn tortilla' },
    { name: 'Breakfast Taco', price: 4, description: 'Scrambled eggs with cheese & salsa', category: 'Tacos', ingredients: 'Scrambled eggs, cheese, pico de gallo, avocado, flour tortilla' },
  ],
};

// Flat list of all items for search
export const ALL_MENU_ITEMS: MenuItem[] = Object.values(MENUS).flat();

// Categories list
export const CATEGORIES = Object.keys(MENUS);
