#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';

export function generateSwiftCode(manifestPath: string, appScheme: string): string {
  const manifests = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  let swiftCode = `import AppIntents
import UIKit

// Auto-generated by react-native-ai-agent
// Do not edit manually.

`;

  for (const intent of manifests) {
    // Convert snake_case to CamelCaseIntent
    const structName = intent.name
      .split('_')
      .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
      .join('') + 'Intent';

    swiftCode += `@available(iOS 16.0, *)\n`;
    swiftCode += `struct ${structName}: AppIntent {\n`;
    swiftCode += `    static var title: LocalizedStringResource = "${intent.name}"\n`;
    swiftCode += `    static var description = IntentDescription("${intent.description.replace(/"/g, '\\"')}")\n`;
    swiftCode += `    static var openAppWhenRun: Bool = true\n\n`;

    // Parameters
    const params = intent.parameters || {};
    for (const [key, param] of Object.entries<any>(params)) {
      let swiftType = 'String';
      if (param.type === 'number') swiftType = 'Double';
      if (param.type === 'boolean') swiftType = 'Bool';
      
      swiftCode += `    @Parameter(title: "${param.description || key}")\n`;
      swiftCode += `    var ${key}: ${swiftType}?\n\n`;
    }

    // Perform function
    swiftCode += `    @MainActor\n`;
    swiftCode += `    func perform() async throws -> some IntentResult {\n`;
    swiftCode += `        var components = URLComponents()\n`;
    swiftCode += `        components.scheme = "${appScheme}"\n`;
    swiftCode += `        components.host = "ai-action"\n`;
    swiftCode += `        components.path = "/${intent.name}"\n`;
    
    if (Object.keys(params).length > 0) {
      swiftCode += `        var queryItems: [URLQueryItem] = []\n`;
      for (const [key, param] of Object.entries<any>(params)) {
        swiftCode += `        if let val = ${key} {\n`;
        swiftCode += `            queryItems.append(URLQueryItem(name: "${key}", value: String(describing: val)))\n`;
        swiftCode += `        }\n`;
      }
      swiftCode += `        components.queryItems = queryItems\n`;
    }

    swiftCode += `        if let url = components.url {\n`;
    swiftCode += `            await UIApplication.shared.open(url)\n`;
    swiftCode += `        }\n`;
    swiftCode += `        return .result()\n`;
    swiftCode += `    }\n`;
    swiftCode += `}\n\n`;
  }

  // AppShortcuts provider (exposes intents to Siri automatically)
  if (manifests.length > 0) {
    swiftCode += `@available(iOS 16.0, *)\n`;
    swiftCode += `struct MobileAIAppShortcuts: AppShortcutsProvider {\n`;
    swiftCode += `    static var appShortcuts: [AppShortcut] {\n`;
    for (const intent of manifests) {
       const structName = intent.name.split('_').map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join('') + 'Intent';
       // Generate a basic short phrase mapping
       swiftCode += `        AppShortcut(intent: ${structName}(), phrases: ["\\\\(.applicationName) ${intent.name.replace(/_/g, ' ')}"])\n`;
    }
    swiftCode += `    }\n`;
    swiftCode += `}\n`;
  }

  return swiftCode;
}

async function main() {
  const manifestPath = process.argv[2] || 'intent-manifest.json';
  const appScheme = process.argv[3] || 'mobileai';
  const outPath = process.argv[4] || 'ios/MobileAIPilotIntents.swift';
  
  const absoluteManifest = path.resolve(process.cwd(), manifestPath);
  const absoluteOut = path.resolve(process.cwd(), outPath);

  if (!fs.existsSync(absoluteManifest)) {
    console.error(`❌ Manifest file not found at ${absoluteManifest}`);
    process.exit(1);
  }

  console.log(`Generating Swift code for schema ${appScheme}...`);
  const swiftCode = generateSwiftCode(absoluteManifest, appScheme);
  
  // Ensure dir exists
  const targetDir = path.dirname(absoluteOut);
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  fs.writeFileSync(absoluteOut, swiftCode);
  console.log(`✅ Wrote Swift AppIntents to ${outPath}`);
}

// Run if called directly
if (require.main === module) {
  main().catch(err => {
    console.error(err);
    process.exit(1);
  });
}
