import AppIntents
import UIKit

// Auto-generated by react-native-ai-agent
// Do not edit manually.

@available(iOS 16.0, *)
struct CheckoutCartIntent: AppIntent {
    static var title: LocalizedStringResource = "checkout_cart"
    static var description = IntentDescription("Process checkout")
    static var openAppWhenRun: Bool = true

    @Parameter(title: "Total amount")
    var amount: Double?

    @Parameter(title: "Currency code")
    var currency: String?

    @Parameter(title: "Express checkout")
    var isExpress: Bool?

    @MainActor
    func perform() async throws -> some IntentResult {
        var components = URLComponents()
        components.scheme = "feedyum"
        components.host = "ai-action"
        components.path = "/checkout_cart"
        var queryItems: [URLQueryItem] = []
        if let val = amount {
            queryItems.append(URLQueryItem(name: "amount", value: String(describing: val)))
        }
        if let val = currency {
            queryItems.append(URLQueryItem(name: "currency", value: String(describing: val)))
        }
        if let val = isExpress {
            queryItems.append(URLQueryItem(name: "isExpress", value: String(describing: val)))
        }
        components.queryItems = queryItems
        if let url = components.url {
            await UIApplication.shared.open(url)
        }
        return .result()
    }
}

@available(iOS 16.0, *)
struct MobileAIAppShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(intent: CheckoutCartIntent(), phrases: ["\\(.applicationName) checkout cart"])
    }
}
